spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/techup_shopping_test}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: create-drop